install:
  options:
    targetDir: './lib'
    layout: 'byType'
    install: true
    verbose: true
    copy: true
    cleanTargetDir: false
    cleanBowerDir: false
    bowerOptions:
      forceLatest: true
      production: false
