install:
  options:
    targetDir: './build/lib'
    layout: 'byType'
    install: true
    verbose: true
    copy: true
    cleanTargetDir: true
    cleanBowerDir: true
    bowerOptions:
      forceLatest: true
      production: false
