assets:
  expand: true
  cwd: 'src/'
  src: 'assets/**'
  dest: 'build/assets/'
  flatten: true
  filter: 'isFile'
partials:
  expand: true
  cwd: 'src/tpl'
  src: 'partials/**'
  dest: 'build/'
  flatten: false
  filter: 'isFile'