assets:
  expand: true
  cwd: 'src/static/'
  src: 'assets/**'
  dest: '<%= cfg.buildDir %>/assets/'
  flatten: true
  filter: 'isFile'
templates:
  expand: true
  cwd: 'src/app/'
  src: '**/*.tpl.html'
  dest: '<%= cfg.buildDir %>/app/'
  flatten: false
  filter: 'isFile'