build:
  options:
    dumpLineNumbers: true
    stripBanners: true
    syncImport: true
    strictImports: true
    paths: ["src/less"]
  src: "src/static/less/app.less"
  dest: "<%= cfg.buildDir %>/css/app.css"
