html:
  files: 'src/**/*.html'
  tasks: 'assemble:build'
  options:
    livereload: true
less:
  files: 'src/**/*.less'
  tasks: 'less:build'
  options:
    livereload: true
js:
  files: 'src/**/*.js'
  tasks: 'browserify:build'
  options:
    livereload: true